worker_processes  auto;

events {
  worker_connections  1024;
}

stream {
  include /etc/nginx/stream.d/*.conf;
}

http {
  include       /etc/nginx/mime.types;
  default_type  application/octet-stream;
  sendfile      on;
  keepalive_timeout  65;

  include /etc/nginx/conf.d/*.conf;
}
